### ISSUE TITLE
RuntimeError:cublas runtime error？

### ISSUE THREAD

**Issue by KiyoshiKAWASAKI** [junyanz/pytorch-CycleGAN-and-pix2pix#76]
Hi I was trying to reproduce your amazing project with the instruction. 
I installed pyTorch and other packages as required in readme, and the training can start without any problem. But after a few epochs, the program was terminates and the error was:

RuntimeError: cublas runtime error : the GPU program failed to execute at /pytorch/torch/lib/THC/THCBlas.cu:246

The full error message was:
model [CycleGANModel] was created
create web directory ./checkpoints/maps_cyclegan/web...
Traceback (most recent call last):
  File "train.py", line 25, in <module>
    model.optimize_parameters()
  File "/media/MMVC_AD/Jin_Huang/pytorch-CycleGAN-and-pix2pix/models/cycle_gan_model.py", line 159, in optimize_parameters
    self.backward_G()
  File "/media/MMVC_AD/Jin_Huang/pytorch-CycleGAN-and-pix2pix/models/cycle_gan_model.py", line 137, in backward_G
    self.fake_B = self.netG_A.forward(self.real_A)
  File "/media/MMVC_AD/Jin_Huang/pytorch-CycleGAN-and-pix2pix/models/networks.py", line 175, in forward
    return nn.parallel.data_parallel(self.model, input, self.gpu_ids)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/parallel/data_parallel.py", line 102, in data_parallel
    return module(*inputs[0], **module_kwargs[0])
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/conv.py", line 566, in forward
    output_padding, self.groups, self.dilation)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/functional.py", line 174, in conv_transpose2d
    return f(input, weight, bias)
RuntimeError: cublas runtime error : the GPU program failed to execute at /pytorch/torch/lib/THC/THCBlas.cu:246

I am using Tesla P100 GPU, the OS is Linux Ubuntu14.
One problem I know is that I don't have CUDA toolkits yet, because when I tried to use nvcc --version to check CUDA version, it shows:
The program 'nvcc' is currently not installed. You can install it by typing:
apt-get install nvidia-cuda-toolkit
You will have to enable the component called 'multiverse'
But I am not sure whether it is related to the cublas runtime error. 

I am new to pyTorch, can you give me some advice on solving this problem? Thank you.

**Comment by Kajiyu** [comment]
I have a same problem.

**Comment by adrianalbert** [comment]
Same problem here -- anyone found a solution?

**Comment by junyanz** [comment]
I think you need to first install the pytorch with cuda/gpu mode and make sure you can run the pytorch test code.

**Comment by ElijahLai** [comment]
Same problem too, does anyone have a solution?

**Comment by junyanz** [comment]
Have you guys installed cudnn? Could you guys run other pytorch demo code on GPU?

**Comment by ElijahLai** [comment]
Yes, I can run RNN with cuda but Attention-based is not working, my GPU is Tesla P100

**Comment by SsnL** [comment]
Hi all, PyTorch developer here. Are all of you seeing this issue using Pascal GPUs? If so, you should make sure that the CUDA version is at least 8.0. 

Also, it would be very helpful if you can provide your PyTorch version (`import torch; print(torch.__Version__)`, CUDA version (`nvcc -V`), and cuDNN version (`grep CUDNN_MAJOR /path/to/cudnn.h`).

**Comment by SsnL** [comment]
@ElijahLai Sorry for missing your response. That is interesting. Could you try uploading to pytorch 0.3 and cuda 9? A number of bugs are fixed in these two releases.

**Comment by XPping** [comment]
I have same problem, and I found my softmax_output=7, but my real_label=8, so I fixed it. May be you should check it out

**Comment by alexteua** [comment]
still happening to me. @XPping how exactly did you make a fix for it?

**Comment by iamxiaoyubei** [comment]
+1
```
WARNING:root:Setting up a new session...
create web directory ./checkpoints/maps_cyclegan/web...
Traceback (most recent call last):
  File "train.py", line 51, in <module>
    model.optimize_parameters()   # calculate loss functions, get gradients, update network weights
  File "/data/xiaoyubei/codes/pytorch-CycleGAN-and-pix2pix/models/cycle_gan_model.py", line 183, in optimize_parameters
    self.forward()      # compute fake images and reconstruction images.
  File "/data/xiaoyubei/codes/pytorch-CycleGAN-and-pix2pix/models/cycle_gan_model.py", line 114, in forward
    self.fake_B = self.netG_A(self.real_A)  # G_A(A)
  File "/home/gongke/miniconda3/envs/pytorch-CycleGAN-and-pix2pix/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gongke/miniconda3/envs/pytorch-CycleGAN-and-pix2pix/lib/python3.5/site-packages/torch/nn/parallel/data_parallel.py", line 121, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/gongke/miniconda3/envs/pytorch-CycleGAN-and-pix2pix/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/xiaoyubei/codes/pytorch-CycleGAN-and-pix2pix/models/networks.py", line 373, in forward
    return self.model(input)
  File "/home/gongke/miniconda3/envs/pytorch-CycleGAN-and-pix2pix/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gongke/miniconda3/envs/pytorch-CycleGAN-and-pix2pix/lib/python3.5/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/gongke/miniconda3/envs/pytorch-CycleGAN-and-pix2pix/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gongke/miniconda3/envs/pytorch-CycleGAN-and-pix2pix/lib/python3.5/site-packages/torch/nn/modules/conv.py", line 691, in forward
    output_padding, self.groups, self.dilation)
RuntimeError: cublas runtime error : the GPU program failed to execute at /opt/conda/conda-bld/pytorch_1533672544752/work/aten/src/THC/THCBlas.cu:249
```
This is my environment:
```
>>> torch.__version__
'0.4.1'
>>> torch.version.cuda
'9.0.176'

$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

```

**Comment by via12** [comment]
> +1
> 
> ```
> WARNING:root:Setting up a new session...
> create web directory ./checkpoints/maps_cyclegan/web...
> Traceback (most recent call last):
>   File "train.py", line 51, in <module>
>     model.optimize_parameters()   # calculate loss functions, get gradients, update network weights
>   File "/data/xiaoyubei/codes/pytorch-CycleGAN-and-pix2pix/models/cycle_gan_model.py", line 183, in optimize_parameters
>     self.forward()      # compute fake images and reconstruction images.
>   File "/data/xiaoyubei/codes/pytorch-CycleGAN-and-pix2pix/models/cycle_gan_model.py", line 114, in forward
>     self.fake_B = self.netG_A(self.real_A)  # G_A(A)
>   File "/home/gongke/miniconda3/envs/pytorch-CycleGAN-and-pix2pix/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/gongke/miniconda3/envs/pytorch-CycleGAN-and-pix2pix/lib/python3.5/site-packages/torch/nn/parallel/data_parallel.py", line 121, in forward
>     return self.module(*inputs[0], **kwargs[0])
>   File "/home/gongke/miniconda3/envs/pytorch-CycleGAN-and-pix2pix/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/data/xiaoyubei/codes/pytorch-CycleGAN-and-pix2pix/models/networks.py", line 373, in forward
>     return self.model(input)
>   File "/home/gongke/miniconda3/envs/pytorch-CycleGAN-and-pix2pix/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/gongke/miniconda3/envs/pytorch-CycleGAN-and-pix2pix/lib/python3.5/site-packages/torch/nn/modules/container.py", line 91, in forward
>     input = module(input)
>   File "/home/gongke/miniconda3/envs/pytorch-CycleGAN-and-pix2pix/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/gongke/miniconda3/envs/pytorch-CycleGAN-and-pix2pix/lib/python3.5/site-packages/torch/nn/modules/conv.py", line 691, in forward
>     output_padding, self.groups, self.dilation)
> RuntimeError: cublas runtime error : the GPU program failed to execute at /opt/conda/conda-bld/pytorch_1533672544752/work/aten/src/THC/THCBlas.cu:249
> ```
> 
> This is my environment:
> 
> ```
> >>> torch.__version__
> '0.4.1'
> >>> torch.version.cuda
> '9.0.176'
> 
> $ nvcc -V
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2018 NVIDIA Corporation
> Built on Sat_Aug_25_21:08:01_CDT_2018
> Cuda compilation tools, release 10.0, V10.0.130
> ```



> +1
> 
> ```
> WARNING:root:Setting up a new session...
> create web directory ./checkpoints/maps_cyclegan/web...
> Traceback (most recent call last):
>   File "train.py", line 51, in <module>
>     model.optimize_parameters()   # calculate loss functions, get gradients, update network weights
>   File "/data/xiaoyubei/codes/pytorch-CycleGAN-and-pix2pix/models/cycle_gan_model.py", line 183, in optimize_parameters
>     self.forward()      # compute fake images and reconstruction images.
>   File "/data/xiaoyubei/codes/pytorch-CycleGAN-and-pix2pix/models/cycle_gan_model.py", line 114, in forward
>     self.fake_B = self.netG_A(self.real_A)  # G_A(A)
>   File "/home/gongke/miniconda3/envs/pytorch-CycleGAN-and-pix2pix/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/gongke/miniconda3/envs/pytorch-CycleGAN-and-pix2pix/lib/python3.5/site-packages/torch/nn/parallel/data_parallel.py", line 121, in forward
>     return self.module(*inputs[0], **kwargs[0])
>   File "/home/gongke/miniconda3/envs/pytorch-CycleGAN-and-pix2pix/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/data/xiaoyubei/codes/pytorch-CycleGAN-and-pix2pix/models/networks.py", line 373, in forward
>     return self.model(input)
>   File "/home/gongke/miniconda3/envs/pytorch-CycleGAN-and-pix2pix/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/gongke/miniconda3/envs/pytorch-CycleGAN-and-pix2pix/lib/python3.5/site-packages/torch/nn/modules/container.py", line 91, in forward
>     input = module(input)
>   File "/home/gongke/miniconda3/envs/pytorch-CycleGAN-and-pix2pix/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/gongke/miniconda3/envs/pytorch-CycleGAN-and-pix2pix/lib/python3.5/site-packages/torch/nn/modules/conv.py", line 691, in forward
>     output_padding, self.groups, self.dilation)
> RuntimeError: cublas runtime error : the GPU program failed to execute at /opt/conda/conda-bld/pytorch_1533672544752/work/aten/src/THC/THCBlas.cu:249
> ```
> 
> This is my environment:
> 
> ```
> >>> torch.__version__
> '0.4.1'
> >>> torch.version.cuda
> '9.0.176'
> 
> $ nvcc -V
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2018 NVIDIA Corporation
> Built on Sat_Aug_25_21:08:01_CDT_2018
> Cuda compilation tools, release 10.0, V10.0.130
> ```

I have the same environment with you. Have you solved it?
Looking forward to your reply. Thanks.

**Comment by junyanz** [comment]
This seems to be related to PyTorch and CUDA. I recommend that you post the question on the PyTorch repo as well. I found a similar issue [here](https://github.com/pytorch/pytorch/issues/7548).

**Comment by via12** [comment]
Thanks a lot.It's very interesting that I have already solved the problem with the help of the link you mentioned.  I forgot to update it here. Thank you again for your reply.

**Comment by via12** [comment]
> This seems to be related to PyTorch and CUDA. I recommend that you post the question on the PyTorch repo as well. I found a similar issue [here](https://github.com/pytorch/pytorch/issues/7548).

Thanks a lot.It's very interesting that I have already solved the problem with the help of the link you mentioned.  I forgot to update it here. Thank you again for your reply.
